/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DeskService } from "../desk.service";
import { DeskCreateInput } from "./DeskCreateInput";
import { Desk } from "./Desk";
import { DeskFindManyArgs } from "./DeskFindManyArgs";
import { DeskWhereUniqueInput } from "./DeskWhereUniqueInput";
import { DeskUpdateInput } from "./DeskUpdateInput";
import { BookingFindManyArgs } from "../../booking/base/BookingFindManyArgs";
import { Booking } from "../../booking/base/Booking";
import { BookingWhereUniqueInput } from "../../booking/base/BookingWhereUniqueInput";

export class DeskControllerBase {
  constructor(protected readonly service: DeskService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Desk })
  async createDesk(@common.Body() data: DeskCreateInput): Promise<Desk> {
    return await this.service.createDesk({
      data: {
        ...data,

        room: data.room
          ? {
              connect: data.room,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        identifier: true,

        room: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Desk] })
  @ApiNestedQuery(DeskFindManyArgs)
  async desks(@common.Req() request: Request): Promise<Desk[]> {
    const args = plainToClass(DeskFindManyArgs, request.query);
    return this.service.desks({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        identifier: true,

        room: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Desk })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async desk(
    @common.Param() params: DeskWhereUniqueInput
  ): Promise<Desk | null> {
    const result = await this.service.desk({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        identifier: true,

        room: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Desk })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateDesk(
    @common.Param() params: DeskWhereUniqueInput,
    @common.Body() data: DeskUpdateInput
  ): Promise<Desk | null> {
    try {
      return await this.service.updateDesk({
        where: params,
        data: {
          ...data,

          room: data.room
            ? {
                connect: data.room,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          identifier: true,

          room: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Desk })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteDesk(
    @common.Param() params: DeskWhereUniqueInput
  ): Promise<Desk | null> {
    try {
      return await this.service.deleteDesk({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          identifier: true,

          room: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/bookings")
  @ApiNestedQuery(BookingFindManyArgs)
  async findBookings(
    @common.Req() request: Request,
    @common.Param() params: DeskWhereUniqueInput
  ): Promise<Booking[]> {
    const query = plainToClass(BookingFindManyArgs, request.query);
    const results = await this.service.findBookings(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        startTime: true,
        endTime: true,

        employee: {
          select: {
            id: true,
          },
        },

        desk: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/bookings")
  async connectBookings(
    @common.Param() params: DeskWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        connect: body,
      },
    };
    await this.service.updateDesk({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/bookings")
  async updateBookings(
    @common.Param() params: DeskWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        set: body,
      },
    };
    await this.service.updateDesk({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/bookings")
  async disconnectBookings(
    @common.Param() params: DeskWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        disconnect: body,
      },
    };
    await this.service.updateDesk({
      where: params,
      data,
      select: { id: true },
    });
  }
}
